package rt4;

import com.jogamp.opengl.GL2;
import org.openrs2.deob.annotation.OriginalArg;
import org.openrs2.deob.annotation.OriginalClass;
import org.openrs2.deob.annotation.OriginalMember;
import org.openrs2.deob.annotation.Pc;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.FloatBuffer;

@OriginalClass("client!rd")
public final class LiquidMaterialRenderer implements MaterialRenderer {

	// Should contain the currently-defined ambient scene intensity (from glLightModel).
	@OriginalMember(owner = "client!rd", name = "d", descriptor = "[F")
	public static final float[] currentAmbientLightColor = new float[4];

	@OriginalMember(owner = "client!rd", name = "a", descriptor = "I")
	private int frameNumber = -1;

	// ID of the display list containing commands for OpenGL to execute upon binding this material.
	// Generated by OpenGL in constructor.
	// Note that bindMaterialCommandList + 1 is the ID of the corresponding "unbind" display list.
	@OriginalMember(owner = "client!rd", name = "e", descriptor = "I")
	private int bindMaterialCommandList = -1;

	// ID of the shader program used for rendering liquid materials.
	// Generated by OpenGL in constructor.
	@OriginalMember(owner = "client!rd", name = "c", descriptor = "I")
	private int shaderProgram;

	@OriginalMember(owner = "client!rd", name = "b", descriptor = "Ljava/nio/FloatBuffer;")
	private FloatBuffer noiseBuffer;

	@OriginalMember(owner = "client!rd", name = "<init>", descriptor = "()V")
	public LiquidMaterialRenderer() {
		// Do nothing if shader program and command list has already been set up.
		// Also do nothing if GPU doesn't support the ARB vertex program extension
		// (https://registry.khronos.org/OpenGL/extensions/ARB/ARB_vertex_program.txt)
		// or supports fewer than 2 texture units (as of GL2.1 this is required to be at least 2, but you never know).
		if (this.bindMaterialCommandList < 0 && (GlRenderer.arbVertexProgramSupported && GlRenderer.maxTextureUnits >= 2)) {
			// Create a new ARB vertex program for shader logic.
			// I believe this was the old way of doing custom vertex shader logic prior to GLSL.
			@Pc(19) int[] shaderPrograms = new int[1];
			@Pc(21) GL2 local21 = GlRenderer.gl;
			local21.glGenProgramsARB(1, shaderPrograms, 0);
			this.shaderProgram = shaderPrograms[0];

			// Generate buffer of noise samples for use in the shader program.
			@Pc(42) int[][] local42 = method874(0.4F);
			@Pc(53) int[][] local53 = method874(0.4F);
			@Pc(58) Buffer noise = new Buffer(262144);
			for (@Pc(60) int i = 0; i < 256; i++) {
				@Pc(67) int[] local67 = local42[i];
				@Pc(71) int[] local71 = local53[i];
				for (@Pc(73) int local73 = 0; local73 < 64; local73++) {
					if (GlRenderer.bigEndian) {
						noise.pFloat((float) local67[local73] / 4096.0F);
						noise.pFloat((float) local71[local73] / 4096.0F);
						noise.pFloat(1.0F);
						noise.pFloat(1.0F);
					} else {
						noise.gFloat((float) local67[local73] / 4096.0F);
						noise.gFloat((float) local71[local73] / 4096.0F);
						noise.gFloat(1.0F);
						noise.gFloat(1.0F);
					}
				}
			}
			@Pc(141) ByteBuffer finalBuffer = ByteBuffer.allocateDirect(noise.offset).order(ByteOrder.nativeOrder());
			finalBuffer.put(noise.data, 0, noise.offset);
			finalBuffer.flip();
			this.noiseBuffer = finalBuffer.asFloatBuffer().asReadOnlyBuffer();

			// Construct the shader.
			this.initializeCommandLists();
			this.initializeShaderProgram();
		}
	}

	@OriginalMember(owner = "client!cj", name = "a", descriptor = "(ZIIIIIIFB)[[I")
	public static int[][] method874(@OriginalArg(7) float arg0) {
		@Pc(15) int[][] local15 = new int[256][64];
		@Pc(19) TextureOp34 local19 = new TextureOp34();
		local19.anInt648 = (int) (arg0 * 4096.0F);
		local19.anInt642 = 3;
		local19.anInt641 = 4;
		local19.aBoolean44 = false;
		local19.anInt646 = 8;
		local19.postDecode();
		Texture.setSize(256, 64);
		for (@Pc(46) int local46 = 0; local46 < 256; local46++) {
			local19.method584(local46, local15[local46]);
		}
		return local15;
	}

	@OriginalMember(owner = "client!rd", name = "a", descriptor = "()V")
	@Override
	public final void unbind() {
		// Run the commands in the command list to unbind the material.
		// Note that the unbind command list's id is the bind command list id + 1.
		if (this.bindMaterialCommandList >= 0) {
			@Pc(5) GL2 gl = GlRenderer.gl;
			gl.glCallList(this.bindMaterialCommandList + 1);
		}
	}

	@OriginalMember(owner = "client!rd", name = "c", descriptor = "()I")
	@Override
	public final int getFlags() {
		return 0;
	}

	@OriginalMember(owner = "client!rd", name = "b", descriptor = "()V")
	@Override
	public final void bind() {
		// If display list failed to create, can't do anything.
		if (this.bindMaterialCommandList < 0) {
			return;
		}
		
		@Pc(5) GL2 gl = GlRenderer.gl;

		// Run the commands in the command list to bind the material.
		gl.glCallList(this.bindMaterialCommandList);

		// Create a texture matrix for this frame of the shader.
		// This basically copies the view matrix of the camera so the texture follows the model.
		gl.glActiveTexture(GL2.GL_TEXTURE1);
		gl.glMatrixMode(GL2.GL_TEXTURE);
		gl.glTranslatef((float) MaterialManager.cameraPositionX, (float) MaterialManager.cameraPositionY, (float) MaterialManager.cameraPositionZ);
		gl.glRotatef(-((float) MaterialManager.cameraYaw * 360.0F) / 2048.0F, 0.0F, 1.0F, 0.0F);
		gl.glRotatef(-((float) MaterialManager.cameraPitch * 360.0F) / 2048.0F, 1.0F, 0.0F, 0.0F);
		gl.glRotatef(-180.0F, 1.0F, 0.0F, 0.0F);
		gl.glMatrixMode(GL2.GL_MODELVIEW);

		// If 3D textures are not supported by hardware, we can't animate the texture within the shader pipeline,
		// so we have to re-bind a new texture each frame.
		// Here, we look up the 2D texture in a pre-built map of texture keyframes,
		// and then bind that 2D texture so it gets loaded into the shader program.
		// 3.125 frames per texture, loop after 64 textures (200 frames).
		if (!MaterialManager.allows3DTextureMapping) {
			gl.glBindTexture(GL2.GL_TEXTURE_2D, MaterialManager.texture2dKeyframes[(int) ((float) (GlRenderer.frameNumber * 64) * 0.005F) % 64]);
		}

		// Swap to texture 0
		gl.glActiveTexture(GL2.GL_TEXTURE0);

		// Avoid duplicate calculations for the same frame.
		if (this.frameNumber == GlRenderer.frameNumber) {
			return;
		}

		// Populate noise values in shader program.
		// Each program parameter is a vec4, but only x and y are used in the program.
		@Pc(85) int noiseBufferIndex = (GlRenderer.frameNumber & 0xFF) * 256;
		for (@Pc(87) int parameterIndex = 0; parameterIndex < 64; parameterIndex++) {
			this.noiseBuffer.position(noiseBufferIndex);
			gl.glProgramLocalParameter4fvARB(GL2.GL_VERTEX_PROGRAM_ARB, parameterIndex, this.noiseBuffer);
			noiseBufferIndex += 4;
		}

		// Set the time parameter in the shader program (local parameter 65).
		// This is only necessary for 3D textures since 2D textures are animated using multiple textures.
		if (MaterialManager.allows3DTextureMapping) {
			gl.glProgramLocalParameter4fARB(GL2.GL_VERTEX_PROGRAM_ARB, 65, (float) GlRenderer.frameNumber * 0.005F, 0.0F, 0.0F, 1.0F);
		} else {
			gl.glProgramLocalParameter4fARB(GL2.GL_VERTEX_PROGRAM_ARB, 65, 0.0F, 0.0F, 0.0F, 1.0F);
		}

		this.frameNumber = GlRenderer.frameNumber;
	}

	// Initializes the "bind" and "unbind" display lists,
	// which are sets of OpenGL commands that can be configured up front and then run repeatedly.
	// These command lists set up configuration for two textures that comprise the liquid material.
	//
	// Not sure what these textures are, but texture 0 seems to be a "noise" layer that has some random
	// movement around the xyz space, while texture 1 seems to be an animated layer with multiple
	// texture "frames", which can either be multiple 2D textures one after another, or can be a 
	// single 3D texture where each slice along the z axis represents a single frame of the animation.
	@OriginalMember(owner = "client!rd", name = "e", descriptor = "()V")
	private void initializeCommandLists() {
		@Pc(1) GL2 gl = GlRenderer.gl;

		// Create two display lists of commands, one for binding the material, and one for unbinding it.
		this.bindMaterialCommandList = gl.glGenLists(2);

		// Configure bind operation.
		gl.glNewList(this.bindMaterialCommandList, GL2.GL_COMPILE);

		// Texture 1 is the animated layer.
		// Color is added to layer below (I think that would be texture 0?)
		gl.glActiveTexture(GL2.GL_TEXTURE1);
		if (MaterialManager.allows3DTextureMapping) {
			gl.glBindTexture(GL2.GL_TEXTURE_3D, MaterialManager.texture3D);
		}
		gl.glTexEnvi(GL2.GL_TEXTURE_ENV, GL2.GL_COMBINE_RGB, GL2.GL_ADD);
		gl.glTexEnvi(GL2.GL_TEXTURE_ENV, GL2.GL_COMBINE_ALPHA, GL2.GL_REPLACE);
		gl.glTexEnvi(GL2.GL_TEXTURE_ENV, GL2.GL_SRC0_ALPHA, GL2.GL_PREVIOUS);

		// Texture 0 is the texture layer that moves around based on noise, not keyframes.
		gl.glActiveTexture(GL2.GL_TEXTURE0);

		// Enable the vertex shader program.
		gl.glBindProgramARB(GL2.GL_VERTEX_PROGRAM_ARB, this.shaderProgram);
		gl.glEnable(GL2.GL_VERTEX_PROGRAM_ARB);
		gl.glEndList();

		// Configure unbind operation.
		gl.glNewList(this.bindMaterialCommandList + 1, GL2.GL_COMPILE);

		// Reset the texture matrix.
		gl.glActiveTexture(GL2.GL_TEXTURE1);
		gl.glMatrixMode(GL2.GL_TEXTURE);
		gl.glLoadIdentity();
		gl.glMatrixMode(GL2.GL_MODELVIEW);

		// Revert texture blending mode back to multiply.
		gl.glTexEnvi(GL2.GL_TEXTURE_ENV, GL2.GL_COMBINE_RGB, GL2.GL_MODULATE);
		gl.glTexEnvi(GL2.GL_TEXTURE_ENV, GL2.GL_COMBINE_ALPHA, GL2.GL_MODULATE);
		gl.glTexEnvi(GL2.GL_TEXTURE_ENV, GL2.GL_SRC0_ALPHA, GL2.GL_TEXTURE);

		// Disable 3D textures.
		gl.glDisable(MaterialManager.allows3DTextureMapping ? GL2.GL_TEXTURE_3D : GL2.GL_TEXTURE_2D);

		// Unbind and disable the vertex shader program.
		gl.glActiveTexture(GL2.GL_TEXTURE0);
		gl.glBindProgramARB(GL2.GL_VERTEX_PROGRAM_ARB, 0);
		gl.glDisable(GL2.GL_VERTEX_PROGRAM_ARB);
		gl.glDisable(GL2.GL_FRAGMENT_PROGRAM_ARB);
		gl.glEndList();
	}

	// Initializes the vertex shader program used by OpenGL to render liquid materials.
	// This shader is relatively simple and does the following:
	// - Applies camera transformations
	// - Applies a noise effect to texture 0
	// - Applies keyframe animation to texture 1, if it is a 3D texture
	// - Applies simple ambient lighting
	@OriginalMember(owner = "client!rd", name = "f", descriptor = "()V")
	private void initializeShaderProgram() {
		// If display lists failed to be created, shader is disabled, so do nothing.
		if (this.bindMaterialCommandList < 0) {
			return;
		}

		@Pc(4) GL2 gl = GlRenderer.gl;
		@Pc(7) int[] shaderErrors = new int[1];

		// Bind the liquid material shader.
		gl.glBindProgramARB(GL2.GL_VERTEX_PROGRAM_ARB, this.shaderProgram);

		// Generate the shader program.
		String programText = 
			"!!ARBvp1.0\n" +
			// Vertex attributes.
			// Input vertex position. This is in local coordinate space.
			"ATTRIB  iPos         = vertex.position;\n" +
			// Input vertex color.
			"ATTRIB  iColour      = vertex.color;\n" +

			// Shader outputs.
			// Output vertex position. This will be in clipping coordinate space.
			"OUTPUT  oPos         = result.position;\n" +
			// Output vertex color, after shading effects applied.
			"OUTPUT  oColour      = result.color;\n" +
			// Texture coordinates for the material's two textures.
			"OUTPUT  oTexCoord0   = result.texcoord[0];\n" +
			"OUTPUT  oTexCoord1   = result.texcoord[1];\n" +
			// Fog distance, used for rendering fog effects.
			"OUTPUT  oFogCoord    = result.fogcoord;\n" +

			// Shader parameters.
			// Time, for animated shader effects.
			// If 3D textures are not supported by hardware, time will be 0.
			"PARAM   time         = program.local[65];\n" +
			// Turbulence of generated noise.
			"PARAM   turbulence   = program.local[64];\n" +
			// Ambient light color to apply to scene.
			"PARAM   lightAmbient = program.local[66]; \n" +
			// Projection and model/view matrices for transforming into clipping space.
			"PARAM   pMatrix[4]   = { state.matrix.projection };\n" +
			"PARAM   mvMatrix[4]  = { state.matrix.modelview };\n" +
			// Texture matrix for applying transformations to the texture coordinates (texture 1 only).
			"PARAM   ivMatrix[4]  = { state.matrix.texture[1] };\n" +
			// Random noise values.
			"PARAM   fNoise[64]   = { program.local[0..63] };\n" +

			"TEMP    noise, clipPos, viewPos, worldPos;\n" +
			"ADDRESS noiseAddr;\n" +

			// Apply model/view matrix to transform local-space vertex to view-space.
			"DP4   viewPos.x, mvMatrix[0], iPos;\n" +
			"DP4   viewPos.y, mvMatrix[1], iPos;\n" +
			"DP4   viewPos.z, mvMatrix[2], iPos;\n" +
			"DP4   viewPos.w, mvMatrix[3], iPos;\n" +

			// Apply texture matrix to compute texture coordinates.
			"DP4   worldPos.x, ivMatrix[0], viewPos;\n" +
			"DP4   worldPos.y, ivMatrix[1], viewPos;\n" +
			"DP4   worldPos.z, ivMatrix[2], viewPos;\n" +
			"DP4   worldPos.w, ivMatrix[3], viewPos;\n" +

			// Don't totally know what's going on here but it seems to generate some noise.
			"ADD   noise.x, worldPos.x, worldPos.z;" + 
			"SUB   noise.y, worldPos.z, worldPos.x;" + 
			"MUL   noise, noise, 0.0001220703125;\n" +
			"FRC   noise, noise;\n" +
			"MUL   noise, noise, 64;\n" +
			"ARL   noiseAddr.x, noise.x;\n" +
			"MOV   noise.x, fNoise[noiseAddr.x].x;\n" +
			"ARL   noiseAddr.x, noise.y;\n" +
			"MOV   noise.y, fNoise[noiseAddr.x].y;\n" +
			"MUL   noise, noise, turbulence.x;\n" +

			// Texture 0 is shifted along the x/z axes based on this generated noise.
			"MAD   oTexCoord0, worldPos.xzww, 0.0078125, noise;\n" +
			"MOV   oTexCoord0.w, 1;\n" +

			// Texture 1 is shifted along the z axes based on time.
			// When supported by hardware, 3D textures are used to store multiple keyframes of a texture.
			// This transformation allows the texture to be shifted on the z axis by the frame number,
			// resulting in a different texture each frame.
			// For 2D textures, time will always be 0, so no transformation occurs (a new texture is bound each frame).
			"MUL   oTexCoord1.xy, worldPos.xzww, 0.0009765625;\n" +
			"MOV   oTexCoord1.zw, time.xxxw;\n" +

			// Apply projection matrix to transform view-space vertex into clipping-space.
			"DP4   clipPos.x, pMatrix[0], viewPos;\n" +
			"DP4   clipPos.y, pMatrix[1], viewPos;\n" +
			"DP4   clipPos.z, pMatrix[2], viewPos;\n" +
			"DP4   clipPos.w, pMatrix[3], viewPos;\n" +

			// Apply ambient lighting.
			"MUL   oColour.xyz, iColour, lightAmbient;\n" +
			"MOV   oColour.w, 1;\n" +

			// Render fog effect at maximum draw distance.
			"MOV   oFogCoord.x, clipPos.z;\n" +

			// Set final vertex position to clipping-space coordinates.
			"MOV   oPos, clipPos; \n" +
			"END";

		// Compile the shader.
		gl.glProgramStringARB(GL2.GL_VERTEX_PROGRAM_ARB, GL2.GL_PROGRAM_FORMAT_ASCII_ARB, programText.length(), programText);

		// Check for compilation errors. Though, this check doesn't seem to have any effect.
		gl.glGetIntegerv(GL2.GL_PROGRAM_ERROR_POSITION_ARB, shaderErrors, 0);
		if (shaderErrors[0] != -1) {
			return;
		}
	}

	// For liquid material rendering, this function configures vertex shader program parameters
	// based on the requested 16-bit flags.
	@OriginalMember(owner = "client!rd", name = "a", descriptor = "(I)V")
	@Override
	public final void setArgument(@OriginalArg(0) int flags) {
		// If display lists failed to be created, shader is disabled, so do nothing.
		if (this.bindMaterialCommandList < 0) {
			return;
		}

		// Enable/disable textures based on bit 5 of the bit flags.
		// If bit is set, textures are enabled, otherwise they are disabled.
		// Note that for liquid material rendering, 3D texture mapping is preferred, if enabled.
		@Pc(5) GL2 gl = GlRenderer.gl;
		gl.glActiveTexture(GL2.GL_TEXTURE1);
		if ((flags & 0x80) == 0) {
			gl.glEnable(MaterialManager.allows3DTextureMapping ? GL2.GL_TEXTURE_3D : GL2.GL_TEXTURE_2D);
		} else {
			gl.glDisable(MaterialManager.allows3DTextureMapping ? GL2.GL_TEXTURE_3D : GL2.GL_TEXTURE_2D);
		}

		// Set the ambient light of the material based on bit 6 of the bit flags.
		// If bit is set, ambient light color is set to white, otherwise the current scene's ambient light color is used.
		// Ambient light is passed to the shader program as local parameter 66.
		gl.glActiveTexture(GL2.GL_TEXTURE0);
		if ((flags & 0x40) == 0) {
			gl.glGetFloatv(GL2.GL_LIGHT_MODEL_AMBIENT, currentAmbientLightColor, 0);
			gl.glProgramLocalParameter4fvARB(GL2.GL_VERTEX_PROGRAM_ARB, 66, currentAmbientLightColor, 0);
		} else {
			gl.glProgramLocalParameter4fARB(GL2.GL_VERTEX_PROGRAM_ARB, 66, 1.0F, 1.0F, 1.0F, 1.0F);
		}

		// Set the turbulence of the material based on bits 15 and 16 of the bit flags.
		// The value of bits 15-16 defines what the value is set to.
		// - 0b00 -> 0.025
		// - 0b01 -> 0.025
		// - 0b10 -> 0.05
		// - 0b11 -> 0.1
		// Turbulence is passed to the shader program as local parameter 64; only the x component of the vec4 is used.
		@Pc(58) int turbulenceFlag = flags & 0x3;
		if (turbulenceFlag == 2) {
			gl.glProgramLocalParameter4fARB(GL2.GL_VERTEX_PROGRAM_ARB, 64, 0.05F, 1.0F, 1.0F, 1.0F);
		} else if (turbulenceFlag == 3) {
			gl.glProgramLocalParameter4fARB(GL2.GL_VERTEX_PROGRAM_ARB, 64, 0.1F, 1.0F, 1.0F, 1.0F);
		} else {
			gl.glProgramLocalParameter4fARB(GL2.GL_VERTEX_PROGRAM_ARB, 64, 0.025F, 1.0F, 1.0F, 1.0F);
		}
	}
}
